export const ConfigInterface = {
    gameWidth: '',
    gameHeight: '',
    reelsPosition: { x: '', y: '' },
    playButtonPosition: { x: '', y: '' },
    selectEasyModePosition: { x: '', y: '' },
    FPSDisplayPosition: { x: '', y: '' },
    totalReels: '',
    reelSpinningCycles: '',
    reelSpinningSpeedFactor: [],
    reelShuffleSpinningSpeedFactor: false,
    totalReelCells: '',
    reelCellHeight: '',
    reelCellWidth: '',
    reelVisibleCells: '',
    reelVerticalPadding: '',
    reelHorizontalMargin: '',
  }